apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-server-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yun427/app-rep.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: message-server-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
