apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-server-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yun427/app-rep.git
    targetRevision: main
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: message-server-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
