apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: message-server
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "125m"
