apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: message-server
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
