apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
  labels:
    app: message-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-server
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - name: message-server
        image: 192.168.2.92/jenkins/message-server # 标签将由kustomize添加
        imagePullPolicy: Always
        ports:
        - containerPort: 22339
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: harbor-secret



