apiVersion: v1
kind: Service
metadata:
  name: message-server-service
  labels:
    app: message-server
spec:
  type: NodePort
  selector:
    app: message-server
  ports:
  - protocol: TCP
    port: 22339
    targetPort: 22339
    nodePort: 22339
